[theme]
base = "dark"
primaryColor = "#B8F0F0"
backgroundColor = "#1A6872"
secondaryBackgroundColor = "#1F717A"
textColor = "#F2FCFC"
font = "sans serif"
baseRadius = "small"
borderColor = "#6FAFB4"

[theme.sidebar]
backgroundColor = "#12525B"
secondaryBackgroundColor = "#1F717A"
